config/routes.rb
Rails.application.routes.draw do 
  devise_for :users
  root 'employees#index'

  # get 'hellos/index'
  # get 'tests/index'



  resources :hellos
  resources :accounts
  resources :supliers
  resources :employees
  resources :documents do
   collection do
    get :contact
   end
  end
  resources :tests
  
  # get 'documents/index'

  # get 'documents/contact'


  # resources :hellos

  # post 'documents', to:'documents#create'
  # get 'documents/destroy'
  # delete 'documents/destroy'

  # delete 'employees/:id', to: 'employees#destroy'
  # resources :employees, only: [:index] do 
  #   collection do 
  #     get :create
  #   end
  # end
  # get 'static_pages/about'
  # get 'static_pages/contact'
  # resources :static_pages, only: [:index] do 
  #   collection do 
  #     get :about
  #     get :contact
  #     get :employee
  #     get :detail
  #   end
    # member do 
    #   get :about
    #   get :contact
    # end
  # root 'employees#index'
  # end
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"

  # root 'posts#index'
  # resources :post
  # get 'posts/new'

  # resources :post, only: [:index] do
  #   collection do
  #     # get :show
  #     # get :new
  #     # get :edit
  #     # get :update
  #     # get :create
  #     # get :destroy
  #   end
  # end

  # root 'post#index'
end

app/models/account.rb
class Account < ApplicationRecord
	belongs_to :suplier
end

app/models/appointment.rb
class Appointment < ApplicationRecord
	belongs_to :physician
    belongs_to :patient
end

app/models/appointment1.rb
class Appointment1 < ApplicationRecord
	belongs_to :physician
    belongs_to :patient
end

app/models/author.rb
class Author < ApplicationRecord
	has_many :books
	has_many :third_models, through: books:
end

app/models/book.rb
class Book < ApplicationRecord
  belongs_to :author
  belongs_to :third_model
end

app/models/detail.rb
class Detail < ApplicationRecord
end

app/models/document.rb
class Document < ApplicationRecord
  belongs_to :employee
end

app/models/employee.rb
class Employee < ApplicationRecord
  has_many :documents
  validates :name, :email, :password, :phone, :address, presence:true
end

app/models/patient.rb
class Patient < ApplicationRecord
	has_many :appointment1s
    has_many :physicians, through: :appointment1s
end

app/models/physician.rb
class Physician < ApplicationRecord
	has_many :appointment1s
    has_many :patients, through: :appointment1s
end

app/models/post.rb
class Post < ApplicationRecord
end

app/models/suplier.rb
class Suplier < ApplicationRecord
	has_many :accounts
end

app/models/test.rb
class Test < ApplicationRecord
end

app/models/third_model.rb
class ThirdModel < ApplicationRecord
	has_many :books
	has_many :authors, through: books:
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :confirmable, :trackable
end

app/controllers/employees_controller.rb
class EmployeesController < ApplicationController
  # before_action :authenticate_user!
  def index
    @emp1 = Employee.all
    @doc1 = Document.all

  end

  def show
  	@emp2 = Employee.find(params[:id])
  end

  def new
    @emp3 = Employee.new
  end
  def create
    @emp7 = Employee.create(
    name: params[:employee][:name],
    email: params[:employee][:email],
    password: params[:employee][:password],
    phone: params[:employee][:phone],
    address: params[:employee][:address])
    redirect_to root_path
  end

  def edit
    @emp4 = Employee.find(params[:id])
  end

  def update
    @emp5 = Employee.find(params[:id])
    @emp5.update(
    name: params[:employee][:name],
    email: params[:employee][:email],
    password: params[:employee][:password],
    phone: params[:employee][:phone],
    address: params[:employee][:address])
    redirect_to root_path
  end

  def destroy
    @emp6 = Employee.find(params[:id])
    if @emp6.destroy
      redirect_to root_path
    else
      # message
    end
  end



  # private

  # def employee_params
  #   params.require(:employee).permit(:name,:email,:password,:phone,:address)
  # end
end

app/helpers/accounts_helper.rb
module AccountsHelper
end

app/helpers/document_helper.rb
module DocumentHelper
end

app/helpers/employee_helper.rb
module EmployeeHelper
end

app/helpers/hello_helper.rb
module HelloHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/supliers_helper.rb
module SupliersHelper
end

app/helpers/test_helper.rb
module TestHelper
end

app/views/employees/_form.html.erb
<h1 class="py-4 text-center">Add Users</h1>
<div class="container row col-md-8 mx-auto shadow p-3">
    <%= form_with model: @employees do |form| %>
		<div class="mb-3">
			<%= form.label :Name , class: 'mb-2' %>
			<%= form.text_field :name , class: 'form-control' %>
		</div>
		<div class="mb-3">
			<%= form.label :Email , class: 'mb-2' %>
			<%= form.email_field :email , class: 'form-control' %>
		</div>
		<div class="mb-3">
			<%= form.label :Password , class: 'mb-2' %>
			<%= form.password_field :password , class: 'form-control' %>
		</div>
		<div class="mb-3">
			<%= form.label :Phone , class: 'mb-2' %>
			<%= form.number_field :phone , class: 'form-control' %>
		</div>
		<div class="mb-3">
			<%= form.label :Address , class: 'mb-2' %>
			<%= form.text_field :address , class: 'form-control' %>
		</div>
		<div class="mb-3">
			<%= form.submit class: 'btn btn-primary' %>
		</div>
	<% end %>
</div>

app/views/employees/contact.html.erb
<%= render :partial => 'form', locals: {static_pages: @static_pages} %>

app/views/employees/edit.html.erb
<h4 class="py-1 text-center">Update Employee</h4>
<div class="container row col-md-8 mx-auto shadow p-3">
    <%= form_with model: @emp4 do |form| %>
    <div class="mb-3">
      <%= form.label :Name , class: 'mb-2' %>
      <%= form.text_field :name , class: 'form-control' %>
    </div>
    <div class="mb-3">
      <%= form.label :Email , class: 'mb-2' %>
      <%= form.email_field :email , class: 'form-control' %>
    </div>
    <div class="mb-3">
      <%= form.label :Password , class: 'mb-2' %>
      <%= form.text_field :password , class: 'form-control' %>
    </div>
    <div class="mb-3">
      <%= form.label :Phone , class: 'mb-2' %>
      <%= form.number_field :phone , class: 'form-control' %>
    </div>
    <div class="mb-3">
      <%= form.label :Address , class: 'mb-2' %>
      <%= form.text_field :address , class: 'form-control' %>
    </div>
    <div class="mb-3">
      <%= form.submit class: 'btn btn-primary' %>
    </div>
  <% end %>
</div>

app/views/employees/index.html.erb
<div class="container">
	
	<table class="table">
		<h4 class="py-2 text-center">This is Employees Model</h4>
		<%= link_to 'Add to Employee', new_employee_path, class: 'btn btn-primary my-2' %>
		<thead class="table-dark">
			<tr>
				<th>Id</th>
				<th>Name</th>
				<th>Email</th>
				<th>Password</th>
				<th>Phone</th>
				<th>Address</th>
				<th>Action</th>
			</tr>
		</thead>
	<% @emp1.each do |e| %>
		<tbody>
			<tr>
				<td><%= e.id %></td>
				<td><%= e.name %></td>
				<td><%= e.email %></td>
				<td><%= e.password %></td>
				<td><%= e.phone %></td>
				<td><%= e.address %></td>
				<td class="d-flex">
					<%= link_to 'Edit', edit_employee_path(e), class: 'btn btn-primary mx-2' %>
					<%= link_to 'View', employee_path(e), class: 'btn btn-success mx-2' %>
					<%= button_to 'Delete', employee_path(e), class: 'btn btn-danger mx-2', method: :delete %>
				</td>
				
			<tr/>
		</tbody>
	<% end %>
	</table>


	
</div>

app/views/employees/new.html.erb
<h4 class="py-1 text-center">Add Employee</h4>
<div class="container row col-md-8 mx-auto shadow p-3">
  <%= form_with model: @emp3 do |form| %>
    <div class="mb-3">
      <%= form.label :Name , class: 'mb-2' %>
      <%= form.text_field :name , class: 'form-control' %>
    </div>
    <div class="mb-3">
      <%= form.label :Email , class: 'mb-2' %>
      <%= form.email_field :email , class: 'form-control' %>
    </div>
    <div class="mb-3">
      <%= form.label :Password , class: 'mb-2' %>
      <%= form.text_field :password , class: 'form-control' %>
    </div>
    <div class="mb-3">
      <%= form.label :Phone , class: 'mb-2' %>
      <%= form.number_field :phone , class: 'form-control' %>
    </div>
    <div class="mb-3">
      <%= form.label :Address , class: 'mb-2' %>
      <%= form.text_field :address , class: 'form-control' %>
    </div>
    <div class="mb-3">
      <%= form.submit class: 'btn btn-primary' %>
    </div>
  <% end %>
</div>

app/views/employees/show.html.erb
<div class="container">
	<h2 class="text-center card my-2">Employee Detail</h2>
	<div class="row shadow p-3">
		<div class="col-md-8 col-lg-8 col-sm-12 mx-auto">
			<div class="row text-center">
				<div class="col-md-6 col-lg-6 col-sm-12 card">
					<p class="card my-2">Id</p>
					<p class="card">Name</p>
					<p class="card">Email</p>
					<p class="card">Password</p>
					<p class="card">Phone</p>
					<p class="card">Address</p>
				</div>
				<div class="col-md-6 col-lg-6 col-sm-12 card">
					<p class="card my-2"><%= @emp2.id %></p>
					<p class="card"><%= @emp2.name %></p>
					<p class="card"><%= @emp2.email %></p>
					<p class="card"><%= @emp2.password %></p>
					<p class="card"><%= @emp2.phone %></p>
					<p class="card"><%= @emp2.address %></p>
				</div>
			</div>
		</div>
	</div>
</div>