config/routes.rb
Rails.application.routes.draw do 
  devise_for :users
  root 'employees#index'

  # get 'hellos/index'
  # get 'tests/index'



  resources :hellos
  resources :accounts
  resources :supliers
  resources :employees
  resources :documents do
   collection do
    get :contact
   end
  end
  resources :tests
  
  # get 'documents/index'

  # get 'documents/contact'


  # resources :hellos

  # post 'documents', to:'documents#create'
  # get 'documents/destroy'
  # delete 'documents/destroy'

  # delete 'employees/:id', to: 'employees#destroy'
  # resources :employees, only: [:index] do 
  #   collection do 
  #     get :create
  #   end
  # end
  # get 'static_pages/about'
  # get 'static_pages/contact'
  # resources :static_pages, only: [:index] do 
  #   collection do 
  #     get :about
  #     get :contact
  #     get :employee
  #     get :detail
  #   end
    # member do 
    #   get :about
    #   get :contact
    # end
  # root 'employees#index'
  # end
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"

  # root 'posts#index'
  # resources :post
  # get 'posts/new'

  # resources :post, only: [:index] do
  #   collection do
  #     # get :show
  #     # get :new
  #     # get :edit
  #     # get :update
  #     # get :create
  #     # get :destroy
  #   end
  # end

  # root 'post#index'
end

app/models/account.rb
class Account < ApplicationRecord
	belongs_to :suplier
end

app/models/appointment.rb
class Appointment < ApplicationRecord
	belongs_to :physician
    belongs_to :patient
end

app/models/appointment1.rb
class Appointment1 < ApplicationRecord
	belongs_to :physician
    belongs_to :patient
end

app/models/author.rb
class Author < ApplicationRecord
	has_many :books
	has_many :third_models, through: books:
end

app/models/book.rb
class Book < ApplicationRecord
  belongs_to :author
  belongs_to :third_model
end

app/models/detail.rb
class Detail < ApplicationRecord
end

app/models/document.rb
class Document < ApplicationRecord
  belongs_to :employee
end

app/models/employee.rb
class Employee < ApplicationRecord
  has_many :documents
  validates :name, :email, :password, :phone, :address, presence:true
end

app/models/patient.rb
class Patient < ApplicationRecord
	has_many :appointment1s
    has_many :physicians, through: :appointment1s
end

app/models/physician.rb
class Physician < ApplicationRecord
	has_many :appointment1s
    has_many :patients, through: :appointment1s
end

app/models/post.rb
class Post < ApplicationRecord
end

app/models/suplier.rb
class Suplier < ApplicationRecord
	has_many :accounts
end

app/models/test.rb
class Test < ApplicationRecord
end

app/models/third_model.rb
class ThirdModel < ApplicationRecord
	has_many :books
	has_many :authors, through: books:
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :confirmable, :trackable
end

app/helpers/accounts_helper.rb
module AccountsHelper
end

app/helpers/document_helper.rb
module DocumentHelper
end

app/helpers/hello_helper.rb
module HelloHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/test_helper.rb
module TestHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Demo</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application"%>
    <% javascript_importmap_tags%>
    <%= javascript_include_tag 'bootsrap.min.js' %>


  </head>

  <body>
  <%= render 'shared/head' %>
  <p class="notice"><%= notice %></p>
  <p class="alert"><%= alert %></p>
  <%= yield %>
  <%= render 'shared/foot' %>
  </body>
</html>

app/views/shared/_foot.html.erb
<footer>
	<div class="bg-dark">
		<h5 class="text-center text-white py-3">Footer</h5>
	</div>
</footer>

app/views/shared/_form.html.erb
<h4 class="py-2 text-center">Get In Touch</h4>
<div class="container">
	<div class="row shadow p-3">
		<div class="col-md-6 col-lg-6 col-sm-12 card">
			<%= form_with model: @employees do |form| %>
			<div class="mb-3">
				<%= form.label :Name , class: 'mb-2' %>
				<%= form.text_field :name , class: 'form-control' %>
			</div>
			<div class="mb-3">
				<%= form.label :Email , class: 'mb-2' %>
				<%= form.email_field :email , class: 'form-control' %>
			</div>
			<div class="mb-3">
				<%= form.label :Password , class: 'mb-2' %>
				<%= form.password_field :password , class: 'form-control' %>
			</div>
			<div class="mb-3">
				<%= form.label :Phone , class: 'mb-2' %>
				<%= form.number_field :phone , class: 'form-control' %>
			</div>
			<div class="mb-3">
				<%= form.label :Address , class: 'mb-2' %>
				<%= form.text_field :address , class: 'form-control' %>
			</div>
			<div class="mb-3">
				<%= form.submit class: 'btn btn-primary' %>
			</div>
		</div>
		<div class="col-md-6 col-lg-6 col-sm-12">
			<iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3557.9122464698785!2d75.72115590988955!3d26.906279976553623!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x396db59134cef689%3A0x87a1677f83446523!2sRVJ%20Infotech!5e0!3m2!1sen!2sin!4v1681901091220!5m2!1sen!2sin" width="100%" height="100%" style="border:0;" allowfullscreen="" loading="lazy" referrerpolicy="no-referrer-when-downgrade"></iframe>
		</div>
	</div>
	<% end %>
</div>

app/views/shared/_head.html.erb
<nav class="navbar navbar-expand-lg bg-dark navbar-dark">
  <div class="container ">
    <%= link_to 'Crud Operation',root_path, class:"navbar-brand"  %>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav ms-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <%= link_to 'Employee', root_path, class:"nav-link fw-bold" %>
        </li>
        <li class="nav-item">
          <%= link_to 'Contact', contact_documents_path, class:"nav-link fw-bold" %>
        </li>
        <li class="nav-item">
          <%= link_to 'Document', documents_path, class:"nav-link fw-bold" %> 
        </li>
        <li class="nav-item">
          <%= link_to 'Hello', hellos_path, class:"nav-link fw-bold" %> 
        </li>
        <li class="nav-item">
          <%= link_to 'Test', tests_path, class:"nav-link fw-bold" %> 
        </li> 
         <% if user_signed_in? %>
          <div class="dropdown" class="drop-down">
            <a class="nav-link fw-bold dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            User
            </a>
            <ul class="dropdown-menu">
              <li class="nav-item">
                <a href="javascrit:void(0)" class="nav-link fw-bold text-dark"><%= current_user.email %></a>
              </li>
             
              <li class="nav-item">
                <%= button_to "logout", destroy_user_session_path, method: :delete, class: 'nav-link fw-bold text-dark'  %> 
               </li>
             
            </ul>
          </div> 
        <% else %>
        <li class="nav-item">
          <%= link_to 'Sign in', new_user_session_path, class:"nav-link fw-bold" %> 
        </li> 
        <% end %>

      </ul>
    </div>
  </div>
</nav> 