config/routes.rb
Rails.application.routes.draw do 
  devise_for :users
  root 'employees#index'

  # get 'hellos/index'
  # get 'tests/index'



  resources :hellos
  resources :accounts
  resources :supliers
  resources :employees
  resources :documents do
   collection do
    get :contact
   end
  end
  resources :tests
  
  # get 'documents/index'

  # get 'documents/contact'


  # resources :hellos

  # post 'documents', to:'documents#create'
  # get 'documents/destroy'
  # delete 'documents/destroy'

  # delete 'employees/:id', to: 'employees#destroy'
  # resources :employees, only: [:index] do 
  #   collection do 
  #     get :create
  #   end
  # end
  # get 'static_pages/about'
  # get 'static_pages/contact'
  # resources :static_pages, only: [:index] do 
  #   collection do 
  #     get :about
  #     get :contact
  #     get :employee
  #     get :detail
  #   end
    # member do 
    #   get :about
    #   get :contact
    # end
  # root 'employees#index'
  # end
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"

  # root 'posts#index'
  # resources :post
  # get 'posts/new'

  # resources :post, only: [:index] do
  #   collection do
  #     # get :show
  #     # get :new
  #     # get :edit
  #     # get :update
  #     # get :create
  #     # get :destroy
  #   end
  # end

  # root 'post#index'
end

app/models/account.rb
class Account < ApplicationRecord
	belongs_to :suplier
end

app/models/appointment.rb
class Appointment < ApplicationRecord
	belongs_to :physician
    belongs_to :patient
end

app/models/appointment1.rb
class Appointment1 < ApplicationRecord
	belongs_to :physician
    belongs_to :patient
end

app/models/author.rb
class Author < ApplicationRecord
	has_many :books
	has_many :third_models, through: books:
end

app/models/book.rb
class Book < ApplicationRecord
  belongs_to :author
  belongs_to :third_model
end

app/models/detail.rb
class Detail < ApplicationRecord
end

app/models/document.rb
class Document < ApplicationRecord
  belongs_to :employee
end

app/models/employee.rb
class Employee < ApplicationRecord
  has_many :documents
  validates :name, :email, :password, :phone, :address, presence:true
end

app/models/patient.rb
class Patient < ApplicationRecord
	has_many :appointment1s
    has_many :physicians, through: :appointment1s
end

app/models/physician.rb
class Physician < ApplicationRecord
	has_many :appointment1s
    has_many :patients, through: :appointment1s
end

app/models/post.rb
class Post < ApplicationRecord
end

app/models/suplier.rb
class Suplier < ApplicationRecord
	has_many :accounts
end

app/models/test.rb
class Test < ApplicationRecord
end

app/models/third_model.rb
class ThirdModel < ApplicationRecord
	has_many :books
	has_many :authors, through: books:
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :confirmable, :trackable
end

app/controllers/documents_controller.rb
class DocumentsController < ApplicationController
  before_action :set_document, only: [:show, :edit, :update, :destroy]

  def index
    @documents = Document.all
  end

  def new
    @document = Document.new
    @employees = Employee.all
  end

  def create
    @document = Document.create(document_params)
    # document.employees.id = params[:employee_id]
    redirect_to documents_path
    	
    # if (@document = Document.create(document_params))
	#   redirect_to documents_path	
    # else
	#   render :new
    # end
  end

  def show
  end

  def destroy
    if @document.destroy
	redirect_to documents_path
    else
	# message
    end
  end

  def edit
  end
  def contact
  end

  def update
    @document = Document.find(params[:id])
    if @document.update(document_params)
	  redirect_to documents_path
    end
  end

  private

  def set_document
    @document = Document.find(params[:id])
  end

  def document_params
    params.require(:document).permit(:name, :doc_type, :employee_id)
  end
end

app/helpers/accounts_helper.rb
module AccountsHelper
end

app/helpers/document_helper.rb
module DocumentHelper
end

app/helpers/documents_helper.rb
module DocumentsHelper
end

app/helpers/employee_helper.rb
module EmployeeHelper
end

app/helpers/hello_helper.rb
module HelloHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/supliers_helper.rb
module SupliersHelper
end

app/helpers/test_helper.rb
module TestHelper
end

app/views/documents/contact.html.erb
<%= render 'shared/form' %>

app/views/documents/edit.html.erb
<h1 class="py-4 text-center">Add Users</h1>
<div class="container row col-md-8 mx-auto shadow p-3">
	<%= form_with(model: @document, local: true) do |form| %>
	<div class="mb-3">
		<%= form.label :Name , class: 'mb-2' %>
		<%= form.text_field :name , class: 'form-control' %>
	</div>
	<div class="mb-3">
		<%= form.label :Doc_type , class: 'mb-2' %>
		<%= form.text_field :doc_type , class: 'form-control' %>
	</div>
	<div class="mb-3">
		<%= form.label :Employee_Id , class: 'mb-2' %>
		<%= form.text_field :employee_id , class: 'form-control' %>
	</div>
	<div class="mb-3">
		<%= form.submit :update , class: 'btn btn-primary' %>
	</div>
	<% end %>
</div>

app/views/documents/index.html.erb
<div class="container">
	<table class="table table-stripped table-hover table-bordered">
		<h4 class="text-center py-2">This is Document Model</h4>
		<%= link_to 'Add to Document', new_document_path, class: 'btn btn-primary my-2' %>
		<tbody class="table-dark">
			<tr>
				<th>Id</th>
				<th>Name</th>
				<th>Document Type</th>
				<th>Employee Id</th>
				<th>Employee Name</th>
				<th>Action</th>
			<tr/>
		</tbody>
		<% @documents.each do |d| %>
		<tbody>
			<tr>
				<td><%= d.id %></td>
				<td><%= d.name %></td>
				<td><%= d.doc_type %></td>
				<td><%= d.employee.id %></td>
				<td><%= d.employee.name %></td>
				<td class="d-flex">
					<%= link_to 'Edit', edit_document_path(d), class: 'btn btn-primary mx-2' %>
					<%= link_to 'View', document_path(d), class: 'btn btn-warning mx-2' %>
					<%= button_to 'Delete', document_path(d), class: 'btn btn-danger mx-2', method: :delete %>
				</td>
			<tr/>
		</tbody>
		<% end %>
	</table>
</div>

app/views/documents/new.html.erb
<h1 class="py-4 text-center">Add Document</h1>
<div class="container row col-md-8 mx-auto shadow p-3">
	<%= form_with model: @document do |f| %>
	<div class="mb-3">
		<%= f.label :Name , class: 'mb-2' %>
		<%= f.text_field :name , class: 'form-control' %>
	</div>
	<div class="mb-3">
		<%= f.label :Doc_type , class: 'mb-2' %>
		<%= f.text_field :doc_type , class: 'form-control' %>
	</div>
	<div class="mb-3">
		<%= f.label :Employee_id , class: 'mb-2' %>
		<%= f.select :employee_id,Employee.all.pluck(:name, :id),{prompt: 'select'},{class:'form-control'} %>
	</div>
	<div class="mb-3">
		<%= f.submit :create , class: 'btn btn-primary' %>
	</div>
	<% end %>
</div>

app/views/documents/show.html.erb
<div class="container">
  <div class="row text-center shadow p-3 my-4">
    <h4 class="my-4 card">Details Show</h4>
  	<div class="col-md-6 col-lg-6 col-sm-12 card">
  	  <p class="card mt-2">Id</p>
  	  <p class="card">Name</p>
  	  <p class="card">Doc Type</p>
  	  <p class="card">Employee Id</p>
      <p class="card">Employee Name</p>
  	</div>
  	<div class="col-md-6 col-lg-6 col-sm-12 card">
  	  <p class="card mt-2"><%= @document.id %></p>
  	  <p class="card"><%= @document.name %></p>
  	  <p class="card"><%= @document.doc_type %></p>
  	  <p class="card"><%= @document.employee_id %></p>
      <p class="card"><%= @document.employee.name %></p>
  	</div>
  </div>
</div>